default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^docs/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^docs/

  - repo: https://github.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
      - id: flake8
