# Built from this template : https://github.com/actions/setup-python

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pre-commit pytest
          pip install -r ./$GITHUB_WORKSPACE/dependencies/requirements.txt
      - name: Lint with pre-commit
          run: |
            pre-commit -c ./$GITHUB_WORKSPACE/.pre-commit-config.yaml run --all
      - name: Sphinx build
        run: |
          cd ./docs && sphinx-build -b html ./source ./build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true